kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: objectscale-scaler
  labels:
    app.kubernetes.io/name: objectscale-scaler
subjects:
  - kind: ServiceAccount
    name: objectscale-scaler
    namespace: default
roleRef:
  kind: ClusterRole
  name: objectscale-scaler
  apiGroup: rbac.authorization.k8s.io
