kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: objectscale-scaler
  labels:
    app.kubernetes.io/name: objectscale-scaler
rules:
- apiGroups:
  - ecs.dellemc.com
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - pravega.pravega.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  - events
  - secrets
  - serviceaccounts
  verbs: ["get", "list", "watch"]
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs: ["get", "list", "watch"]
- apiGroups:
  - metrics.k8s.io
  resources:
    - pods
    - nodes
  verbs: ["get", "list", "watch"]
