kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cr-scaler
  labels:
    app.kubernetes.io/name: cr-scaler
subjects:
  - kind: ServiceAccount
    name: cr-scaler
    namespace: nautilus-pravega
roleRef:
  kind: ClusterRole
  name: cr-scaler
  apiGroup: rbac.authorization.k8s.io
